spring.application.name=courseacademy

spring.datasource.url=jdbc:mysql://localhost:3306/courseacademy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123!@#abc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=AffordTech@2026#JWT!Secure$Random%Secret^123456789ABCDEFGHIJKLMNOPQRSTUVbhav
app.jwt.expiration-ms=604800000

razorpay.key.secret=YOUR_RAZORPAY_SECRET

admin.name=bhavyasri
admin.email=nsbhavyasri24@gmail.com
admin.password=Secret@123456789

app.admin.name=bhavyasri
app.admin.email=nsbhavyasri24@gmail.com
app.admin.password=Secret@123456789

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=affordtech123@gmail.com
spring.mail.password=GN8Ni95qkvlgA7eB

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.mail.from=affordtech123@gmail.com

server.port=8080
